name: HelloWolrd

on:
  push:
     branches:
       - 'main'
  job:
    build:
      runs-on: ubuntu-latest
      
      steps:
        - name: Printing Hello World
          run: echo "Hello World!"
